services:
  db:
    container_name: ms_db
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Admin123@
      POSTGRES_DB: ms
    volumes:
      - ./.docker-data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  db:
    driver: bridge
